
version: "3.4"

services:
  restoredata:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - "8080:8080"
    command: ["npm", "start"]  # This will run after the build is complete
