# Stage 1: Build
FROM node:18-alpine as base
WORKDIR /usr/src/app

# Copy package.json and lock files
COPY ["package.json", "package-lock.json*", "npm-shrinkwrap.json*", "./"]

# Install dependencies
RUN npm install

# Copy source files
COPY . .

# Build the project (TypeScript -> JavaScript)
RUN npm run build

# Stage 2: Production
FROM base as production

# Set the node path to the built app
ENV NODE_PATH=./dist

# Expose the necessary ports
EXPOSE 8080

# Set the ownership of the app to the node user
RUN chown -R node /usr/src/app
USER node

# Build the app (in case anything was missed in the build stage)
RUN npm run build

# Start the app in production mode (this runs `npm start`)
CMD ["npm", "start"]
