version: '3.4'

services:
 restoredata:
    image:  restoredata
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 8080:8080
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "dist/src/app.js"]